# .github/workflows/build.yml
name: Deploy Dockerized App

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: nirajan-devops/test-repo/.github/workflows/deploy.yml@main
    with:
      image-name: nextjs-app
      container-name: nextjs-app
      port: "3000"
    secrets:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
