name: Deploy Dockerized App

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: nirajan-devops/test-repo/.github/workflows/ci.yml@main
    with:
      image-name: nextjs-app
      container-name: nextjs-app
      port: "3000"
    secrets:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
